version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "0xNikilite"
    labels:
      - "dependencies"
      - "rust"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "cargo"
