name: PR Safety Check

# Trigger on PR events
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check contributor authorization
        uses: actions/github-script@v6
        id: check-maintainer
        with:
          # List of trusted maintainers
          script: |
            const maintainers = [
              '0xNikilite',  
            ];
            
            const isMaintainer = maintainers.includes(context.actor);
            core.setOutput('is_maintainer', isMaintainer);
            
            if (!isMaintainer) {
              core.notice(`External contributor: ${context.actor}`);
            }
            
      - name: Require manual review for external contributors
        if: ${{ steps.check-maintainer.outputs.is_maintainer == 'false' }}
        uses: actions/github-script@v6
        with:
          script: |
            // Add 'needs-review' label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['needs-review']
            });
            
            // Request review from maintainers
            await github.rest.pulls.createReviewRequest({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['0xNikilite']
            });