name: PR Safety Check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check contributor authorization
        uses: actions/github-script@v6
        id: check-maintainer
        with:
          script: |
            const maintainers = ['0xNikilite'];
            const isMaintainer = maintainers.includes(context.actor);
            core.setOutput('is_maintainer', isMaintainer);
            if (!isMaintainer) {
              core.notice(`External contributor detected: ${context.actor}`);
            }

      - name: Require manual review for external contributors
        if: ${{ steps.check-maintainer.outputs.is_maintainer == 'false' }}
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['needs-review']
              });
            } catch (error) {
              core.warning('GITHUB_TOKEN failed, trying with PAT');
              
              const { Octokit } = require("@octokit/rest");
              const patOctokit = new Octokit({ auth: core.getInput('pat-token') });
              
              await patOctokit.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['needs-review']
              });
            }

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['0xNikilite']
            });
