name: Security Audit

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-audit if needed
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit --locked
          fi

      - name: Run cargo-audit
        run: |
          cargo audit

      - name: Cache cargo bin directory
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-

      - name: Install cargo-outdated if needed
        run: |
          if ! command -v cargo-outdated &> /dev/null; then
            cargo install cargo-outdated --locked
          fi

      - name: Check for outdated dependencies
        run: cargo outdated --exit-code 1 || echo "Outdated dependencies found - not failing build"

      - name: Scan for exposed secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
