name: Security Audit

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Audit dependencies for vulnerabilities
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-outdated if needed
        run: |
          if ! command -v cargo-outdated &> /dev/null; then
            cargo install cargo-outdated --locked
          fi

      - name: Cache cargo bin directory
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-

      - name: Check for outdated dependencies
        run: cargo outdated --exit-code 1

      - name: Scan for exposed secrets
        uses: gitleaks/gitleaks-action@v2
